const userModel=require('../models/userModel');const ticketModel=require('../models/ticketModel');const purchaseModel=require('../models/purchaseModel');const prizeModel=require('../models/prizeModel');const drawModel=require('../models/drawModel');const winnerModel=require('../models/winnerModel');const drawService=require('../services/drawService');
async function dashboard(req,res,next){try{const [users,tickets,purchases,draws]=await Promise.all([userModel.countAll(),ticketModel.countAll(),purchaseModel.countAll(),drawModel.listAll()]);res.render('admin/dashboard',{pageTitle:'Admin Dashboard | PrizeMania',counts:{users,tickets,purchases,draws:draws.length},draws:draws.slice(0,5)});}catch(e){next(e);}}
async function users(req,res,next){try{res.render('admin/list',{pageTitle:'Users | Admin',heading:'Users',columns:['Name','Email','Role','Balance','Joined'],rows:(await userModel.listAll()).map(x=>[x.name,x.email,x.role,`£${Number(x.wallet_balance).toFixed(2)}`,new Date(x.created_at).toLocaleDateString('en-GB')])});}catch(e){next(e);}}
async function tickets(req,res,next){try{res.render('admin/list',{pageTitle:'Tickets | Admin',heading:'Tickets',columns:['Ticket','Owner','Email','Draw','Purchased'],rows:(await ticketModel.listAll()).map(x=>[x.ticket_number,x.user_name,x.email,x.draw_name,new Date(x.purchased_at).toLocaleString('en-GB')])});}catch(e){next(e);}}
async function purchases(req,res,next){try{res.render('admin/list',{pageTitle:'Purchases | Admin',heading:'Purchases',columns:['User','Draw','Quantity','Unit price','Total','Date'],rows:(await purchaseModel.listAll()).map(x=>[x.user_name,x.draw_name,x.quantity,`£${Number(x.unit_price).toFixed(2)}`,`£${Number(x.total_amount).toFixed(2)}`,new Date(x.created_at).toLocaleString('en-GB')])});}catch(e){next(e);}}
async function prizes(req,res,next){try{res.render('admin/prizes',{pageTitle:'Prizes | Admin',prizes:await prizeModel.listAll()});}catch(e){next(e);}}
function prizeData(body){const data={name:String(body.name||'').trim(),description:String(body.description||'').trim(),imagePath:String(body.imagePath||'').trim(),displayOrder:Number(body.displayOrder),isActive:body.isActive?1:0};if(!data.name||!data.description||!data.imagePath||!Number.isInteger(data.displayOrder)||data.displayOrder<1)throw Object.assign(new Error('Complete every prize field with a valid display order.'),{status:400});return data;}
function prizeForm(req,res){res.render('admin/prize-form',{pageTitle:'New Prize | Admin',prize:null});}
async function editPrizeForm(req,res,next){try{const prize=await prizeModel.findById(req.params.id);if(!prize)return next(Object.assign(new Error('Prize not found.'),{status:404}));res.render('admin/prize-form',{pageTitle:'Edit Prize | Admin',prize});}catch(e){next(e);}}
async function createPrize(req,res,next){try{await prizeModel.create(prizeData(req.body));req.flash('success','Prize created.');res.redirect('/admin/prizes');}catch(e){next(e);}}
async function updatePrize(req,res,next){try{await prizeModel.update(req.params.id,prizeData(req.body));req.flash('success','Prize updated.');res.redirect('/admin/prizes');}catch(e){next(e);}}
async function removePrize(req,res,next){try{await prizeModel.remove(req.params.id);req.flash('success','Prize deactivated. Existing winner history is preserved.');res.redirect('/admin/prizes');}catch(e){next(e);}}
async function draws(req,res,next){try{res.render('admin/draws',{pageTitle:'Draws | Admin',draws:await drawModel.listAll()});}catch(e){next(e);}}
function drawForm(req,res){res.render('admin/draw-form',{pageTitle:'New Draw | Admin'});}
async function createDraw(req,res,next){try{const data={name:String(req.body.name||'').trim(),drawDate:req.body.drawDate,ticketPrice:Number(req.body.ticketPrice),status:'draft',opensAt:req.body.opensAt,closesAt:req.body.closesAt};if(!data.name||!data.drawDate||!data.opensAt||!data.closesAt||!(data.ticketPrice>0)||new Date(data.closesAt)<=new Date(data.opensAt))throw Object.assign(new Error('Enter a valid name, positive price, and closing time after the opening time.'),{status:400});await drawModel.create(data);req.flash('success','Draft draw created.');res.redirect('/admin/draws');}catch(e){next(e);}}
async function drawDetails(req,res,next){try{const draw=await drawModel.findById(req.params.id);if(!draw)return next(Object.assign(new Error('Draw not found.'),{status:404}));res.render('admin/draw-details',{pageTitle:`${draw.name} | Admin`,draw,winners:await winnerModel.forDraw(draw.id)});}catch(e){next(e);}}
async function setStatus(req,res,next){try{const allowed={draft:['open'],open:['closed'],closed:['open'],completed:['published']};const draw=await drawModel.findById(req.params.id);if(!draw||!allowed[draw.status]?.includes(req.body.status))throw Object.assign(new Error('That draw status change is not allowed.'),{status:400});if(draw.status==='closed'&&req.body.status==='open'){const winners=await winnerModel.forDraw(draw.id);if(winners.length)throw Object.assign(new Error('A draw cannot be reopened after winners have been selected.'),{status:409});if(new Date(draw.closes_at)<=new Date())throw Object.assign(new Error('Extend the closing time before reopening this expired draw.'),{status:400});}await drawModel.updateStatus(draw.id,req.body.status);req.flash('success',req.body.status==='open'&&draw.status==='closed'?'Draw reopened and ticket purchases are enabled again.':`Draw marked ${req.body.status}.`);res.redirect(`/admin/draws/${draw.id}`);}catch(e){next(e);}}
async function selectWinners(req,res,next){try{await drawService.selectWinners(Number(req.params.id));req.flash('success','Winners selected and saved. Review them before publishing.');res.redirect(`/admin/draws/${req.params.id}`);}catch(e){if(e.status&&e.status<500){req.flash('error',e.message);return res.redirect(`/admin/draws/${req.params.id}`);}next(e);}}
module.exports={dashboard,users,tickets,purchases,prizes,prizeForm,editPrizeForm,createPrize,updatePrize,removePrize,draws,drawForm,createDraw,drawDetails,setStatus,selectWinners};
